---
title: "Assignment 4"
author: "Kazia Mermel"
date: "5/24/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

# Variables:
# temperature at time t
# t = time
# t_diff = T = temperature at time 100 (given)

 #overall value for T

# Givens & Vectors:


t_vector <- seq(1,200, by = 1)
t_diff = 5 # T
B = .05
g = .01
n = .5




```


Structure for Functions 1 - 5 is next.



```{r}
# Functions 1 - 5

# Function 1 - Temperature(t)

temp <- function(t){
  out = t*t_diff/100
  return(out)
}

# Temperature df

temp_df_T_0 <- data.frame(t = t_vector) %>% 
mutate(temp = temp(t_vector)) %>% 
mutate(temp_min = min(temp(t_vector)))

# Function 2 - Retention (t)
retention <- function(t){
  out = exp(-B * (temp(t))^2)
  return(out)
}

# Retention df

retent_df_T_0 <- data.frame(t = t_vector) %>% 
mutate(retent = retention(t_vector)) 

# Function 3 - Consumption (t)
consumption <- function(t){
  out = retention(t) * exp(g*t)
  return(out)
}

# Consumption df

consum_df_T_0 <- data.frame(t = t_vector) %>% 
mutate(consum = consumption(t_vector))

# Function 4 - Utility (C)

C <- consum_df_T_0$consum

utility <- function(C){
  out = (C^(1-n))/(1-n)
  return(out)
}

# Consumption df

utility_df_T_0 <- data.frame(t = t_vector) %>% 
  mutate(consum = C) %>% 
  mutate(utility = utility(C))

# Function 5 - Discount Rate (Ramsey Rule)

r <- function(p){
  out = (d + n*g)
  return(out)
}


```




```{r}
T_0_df <- data.frame(t = t_vector) %>% 
  mutate(tau = temp(t_vector))# %>% 
 # mutate(K = retention(t_vector, temp) )



# fraction of economic activity retained in a year
# r = temperature at time t
# B = some constant we're given
retention = function(t, temp, B)
{out = exp(-B*temp^2)
return(out)}

retention(t = 10, r = temp(t = 50, T = 5), B = 0.05)

# economic activity
# g = some other constant
# K = retention of economic activity in a year
consumption = function(t, g, K)
{out = K*exp(g*t)
return(out)}

consumption(t = 10, g = 0.01, K = retention(t = 10, r = temp(t = 50, T = 5), B = 0.05))

# utility from consumption
# C = consumption
# n = some constant
utility = function(C, n)
{out = C^(1-n)/(1-n)
return(out)}

utility(C = consumption(t = 10, g = 0.01, K = retention(t = 10, r = temp(t = 50, T = 5), B = 0.05)), n = 0.5)

# discount rate, based on Ramsey Rule
# d = delta aka some constant
# n and g are both constants we're given
discount = function(d,n, g)
{out = d + n*g
return(out)}

discount(d = 0.005, n = 0.5, g = 0.01)
```

Question 1
```{r}
# a
# plot temperature over time
# scenario 1: no climate change


# scenario 2: moderate climate change

# scenario 3: major climate change
```

